[versions]
enigma = "2.7.2"

asm = "9.9"
quilt_json_parser = "0.3.1"
tinylog = "2.7.0"
annotations = "23.0.0"
jspecify = "1.0.0"
gson = "2.13.2"

junit = "6.0.1"
hamcrest = "3.0"

dfu = "8.0.16"

[libraries]
enigma = { module = "org.quiltmc:enigma", version.ref = "enigma" }
enigma_swing = { module = "org.quiltmc:enigma-swing", version.ref = "enigma" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm_commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm_tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm_util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
quilt_json5 = { module = "org.quiltmc.parsers:json", version.ref = "quilt_json_parser" }
tinylog = { module = "org.tinylog:tinylog-api", version.ref = "tinylog" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit_launcher = { module = "org.junit.platform:junit-platform-launcher" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }

dfu = { module = "com.mojang:datafixerupper", version.ref = "dfu" }

[bundles]
asm = ["asm", "asm_commons", "asm_tree", "asm_util"]
junit_runtime = ["junit_engine", "junit_launcher"]
